-- 코드를 작성해주세요
SELECT c.ID AS ID, c.GENOTYPE AS GENOTYPE, p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA c
JOIN ECOLI_DATA p on c.PARENT_ID = p.ID
WHERE c.GENOTYPE & p.GENOTYPE = p.GENOTYPE
ORDER BY c.ID ASC;