SELECT DISTINCT d.ID AS ID, d.EMAIL AS EMAIL, d.FIRST_NAME AS FIRST_NAME, d.LAST_NAME AS LAST_NAME
FROM SKILLCODES s
JOIN DEVELOPERS d ON (s.CODE & d.SKILL_CODE !=0)
WHERE s.NAME IN ("Python", "C#")
ORDER BY ID ASC;